import nodemailer from "nodemailer";
import { generateErrorAnalysis } from "./LLMgenerator";
import { prisma } from "../prisma/prisma";
import { LlmType } from "../generated/prisma/enums";

interface SendErrorAnalysisEmailParams {
    smtpUsername: string;
    smtpPassword: string;
    fromEmail: string;
    toEmail: string;
    llmProvider: "openai" | "claude" | "gemini";
    llmApiKey: string;
    llmModel: string;
    errorMessage: string;
    projectId: string;
}

async function sendErrorAnalysisEmail(
    params: SendErrorAnalysisEmailParams
): Promise<{ success: boolean; errorLogId?: string; error?: string }> {
    const {
        smtpUsername,
        smtpPassword,
        fromEmail,
        toEmail,
        llmProvider,
        llmApiKey,
        llmModel,
        errorMessage,
        projectId,
    } = params;

    try {
        // Generate error analysis using LLM
        const analysis = await generateErrorAnalysis(
            llmProvider,
            llmApiKey,
            llmModel,
            errorMessage
        );

        // Map provider to LlmType enum
        const llmTypeMap: Record<string, LlmType> = {
            openai: LlmType.openai,
            claude: LlmType.claude,
            gemini: LlmType.google,
        };

        // Save to database
        const errorLog = await prisma.errorLog.create({
            data: {
                projectId,
                error: errorMessage,
                LLmType: llmTypeMap[llmProvider],
                resolution: JSON.stringify(analysis),
            },
        });

        // Create transporter
        const transporter = nodemailer.createTransport({
            host: "smtp.gmail.com", // Default to Gmail, can be parameterized
            port: 587,
            secure: false, // true for 465, false for other ports
            auth: {
                user: smtpUsername,
                pass: smtpPassword,
            },
        });

        // Email content
        const emailHtml = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f4f4f4;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .section {
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 15px;
        }
        .section-title {
            color: #2c3e50;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .error-box {
            background-color: #fee;
            border-left: 4px solid #c00;
            padding: 10px;
            margin: 10px 0;
        }
        .solution-box {
            background-color: #efe;
            border-left: 4px solid #0c0;
            padding: 10px;
            margin: 10px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>Error Analysis Report - Notaify</h2>
        </div>
        
        <div class="section">
            <div class="section-title">📍 Location:</div>
            <p>${analysis.location}</p>
        </div>
        
        <div class="section">
            <div class="section-title">⚠️ Error Message:</div>
            <div class="error-box">
                <code>${errorMessage}</code>
            </div>
        </div>
        
        <div class="section">
            <div class="section-title">🔍 Reason:</div>
            <p>${analysis.reason}</p>
        </div>
        
        <div class="section">
            <div class="section-title">✅ Solution:</div>
            <div class="solution-box">
                <p>${analysis.solution}</p>
            </div>
        </div>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px;">
            <p>This analysis was generated by ${llmProvider} using ${llmModel}</p>
            <p>Error Log ID: ${errorLog.id}</p>
            <p>Timestamp: ${new Date().toLocaleString()}</p>
        </div>
    </div>
</body>
</html>
        `;

        // Send email
        await transporter.sendMail({
            from: fromEmail,
            to: toEmail,
            subject: `Error Analysis Report - ${new Date().toLocaleDateString()}`,
            html: emailHtml,
        });

        return {
            success: true,
            errorLogId: errorLog.id,
        };
    } catch (error) {
        console.error("Error in sendErrorAnalysisEmail:", error);
        return {
            success: false,
            error: error instanceof Error ? error.message : "Unknown error",
        };
    }
}

interface SampleErrorMailParams {
    smtpUsername: string;
    smtpPassword: string;
    fromEmail: string;
    toEmail: string;
    llmProvider: "openai" | "claude" | "gemini";
    llmApiKey: string;
    llmModel: string;
    projectId: string;
}

async function sampleErrorMail(
    params: SampleErrorMailParams
): Promise<{ success: boolean; errorLogId?: string; error?: string }> {
    const {
        smtpUsername,
        smtpPassword,
        fromEmail,
        toEmail,
        llmProvider,
        llmApiKey,
        llmModel,
        projectId,
    } = params;

    // Create a sample error for testing
    const sampleErrorMessage = `TypeError: Cannot read property 'map' of undefined at Array.filter (line 42, column 15)`;

    try {
        // Generate error analysis using LLM
        const analysis = await generateErrorAnalysis(
            llmProvider,
            llmApiKey,
            llmModel,
            sampleErrorMessage
        );

        // Map provider to LlmType enum
        const llmTypeMap: Record<string, LlmType> = {
            openai: LlmType.openai,
            claude: LlmType.claude,
            gemini: LlmType.google,
        };

        // Save to database
        const errorLog = await prisma.errorLog.create({
            data: {
                projectId,
                error: sampleErrorMessage,
                LLmType: llmTypeMap[llmProvider],
                resolution: JSON.stringify(analysis),
            },
        });

        // Create transporter
        const transporter = nodemailer.createTransport({
            host: "smtp.gmail.com",
            port: 587,
            secure: false,
            auth: {
                user: smtpUsername,
                pass: smtpPassword,
            },
        });

        // Email content with test notice
        const emailHtml = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f4f4f4;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .test-banner {
            background-color: #fff3cd;
            border: 2px solid #ffc107;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 20px;
            text-align: center;
            font-weight: bold;
            color: #856404;
        }
        .section {
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 15px;
        }
        .section-title {
            color: #2c3e50;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .error-box {
            background-color: #fee;
            border-left: 4px solid #c00;
            padding: 10px;
            margin: 10px 0;
        }
        .solution-box {
            background-color: #efe;
            border-left: 4px solid #0c0;
            padding: 10px;
            margin: 10px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="test-banner">
            ⚠️ TEST ERROR MAIL - For Testing Purposes Only ⚠️
        </div>
        
        <div class="header">
            <h2>Sample Error Analysis Report - Notaify</h2>
            <p style="color: #666; margin: 10px 0 0 0;">This is a test email to verify your error analysis system is working correctly.</p>
        </div>
        
        <div class="section">
            <div class="section-title">📍 Location:</div>
            <p>${analysis.location}</p>
        </div>
        
        <div class="section">
            <div class="section-title">⚠️ Sample Error Message:</div>
            <div class="error-box">
                <code>${sampleErrorMessage}</code>
            </div>
        </div>
        
        <div class="section">
            <div class="section-title">🔍 Reason:</div>
            <p>${analysis.reason}</p>
        </div>
        
        <div class="section">
            <div class="section-title">✅ Solution:</div>
            <div class="solution-box">
                <p>${analysis.solution}</p>
            </div>
        </div>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px;">
            <p><strong>Test Information:</strong></p>
            <p>This analysis was generated by ${llmProvider} using ${llmModel}</p>
            <p>Error Log ID: ${errorLog.id}</p>
            <p>Timestamp: ${new Date().toLocaleString()}</p>
            <p style="margin-top: 10px; font-style: italic;">This is a sample error email for testing purposes. No actual error has occurred in your application.</p>
        </div>
    </div>
</body>
</html>
        `;

        // Send email
        await transporter.sendMail({
            from: fromEmail,
            to: toEmail,
            subject: `[TEST] Sample Error Analysis Report - ${new Date().toLocaleDateString()}`,
            html: emailHtml,
        });

        return {
            success: true,
            errorLogId: errorLog.id,
        };
    } catch (error) {
        console.error("Error in sampleErrorMail:", error);
        return {
            success: false,
            error: error instanceof Error ? error.message : "Unknown error",
        };
    }
}

export { sendErrorAnalysisEmail, sampleErrorMail };
export type { SendErrorAnalysisEmailParams, SampleErrorMailParams };